### ISSUE TITLE
composer invalid?

### ISSUE THREAD

**Issue by loeken** [alexschwarz89/icecatxml#1]
composer.json update (phar) with "alexschwarz89/icecatxml": "*" results in:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package alexschwarz89/icecatxml could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by alexschwarz89** [comment]
I think i forgot to made it available to public at packagist, which i did now. For now, please set your minimum stability to dev to require it:

inside your composer.json
`"minimum-stability": "dev"`

I will create a version v1.0 later, so you can use it without the minium-stability setting.

Best regards & thanks

**Comment by alexschwarz89** [comment]
I tagged the versions and removed the minimum-stability, so you can require it as described in readme.md

**Comment by loeken** [comment]
thanks that seemed to almost have worked - if there wasnt guzzle v 5.3
do you happen to know if its working with guzzle ^6.0 aswell? I use it along a few other composer projects which require guzzle 6.

**Comment by alexschwarz89** [comment]
Hi @loeken, i've published version 1.1.0 that uses the newest version of guzzle.

**Comment by loeken** [comment]
thanks
